spring:
  application:
    name: task-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: redis

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: task-service
logging:
  pattern:
    level: "%d{yyyy-MM-dd HH:mm:ss} %-5level [${spring.application.name},%X{traceId:-},%X{spanId:-}] %msg%n"
